const products = [
  {
    id: 1,
    img: '/product1.svg',
    name: 'Bosch 300 Series SHEM63W55N',
    price: 998,
    discountPrice: 1200,
    cartIcon: 'src/utilities/CartIcon.jsx',
  },
  {
    id: 2,
    img: '/product2.svg',
    name: 'Bosch 300 Series SHEM63W55N',
    price: 998,
    discountPrice: 1200,
    cartIcon: 'src/utilities/CartIcon.jsx',
  },
  {
    id: 3,
    img: '/product3.svg',
    name: 'Bosch 300 Series SHEM63W55N',
    price: 998,
    discountPrice: 1200,
    cartIcon: 'src/utilities/CartIcon.jsx',
  },
  {
    id: 4,
    img: '/product4.svg',
    name: 'Bosch 300 Series SHEM63W55N',
    price: 998,
    discountPrice: 1200,
    cartIcon: 'src/utilities/CartIcon.jsx',
  },
  {
    id: 5,
    img: '/product5.svg',
    name: 'Bosch 300 Series SHEM63W55N',
    price: 998,
    discountPrice: 1200,
    cartIcon: 'src/utilities/CartIcon.jsx',
  },
  {
    id: 6,
    img: '/product6.svg',
    name: 'Bosch 300 Series SHEM63W55N',
    price: 998,
    discountPrice: 1200,
    cartIcon: 'src/utilities/CartIcon.jsx',
  },
  {
    id: 7,
    img: '/product7.svg',
    name: 'Bosch 300 Series SHEM63W55N',
    price: 998,
    discountPrice: 1200,
    cartIcon: 'src/utilities/CartIcon.jsx',
  },
  {
    id: 8,
    img: '/product8.svg',
    name: 'Bosch 300 Series SHEM63W55N',
    price: 998,
    discountPrice: 1200,
    cartIcon: 'src/utilities/CartIcon.jsx',
  },
  {
    id: 9,
    img: '/product9.svg',
    name: 'Bosch 300 Series SHEM63W55N',
    price: 998,
    discountPrice: 1200,
    cartIcon: 'src/utilities/CartIcon.jsx',
  },
  {
    id: 10,
    img: '/product10.svg',
    name: 'Bosch 300 Series SHEM63W55N',
    price: 998,
    discountPrice: 1200,
    cartIcon: 'src/utilities/CartIcon.jsx',
  },
  {
    id: 11,
    img: '/product11.svg',
    name: 'Bosch 300 Series SHEM63W55N',
    price: 998,
    discountPrice: 1200,
    cartIcon: 'src/utilities/CartIcon.jsx',
  },
];
export default products;
